sudo: required
services:
  - docker

before_install:
  - docker build -t pcofilada/personal-website -f Dockerfile.dev .

script:
  - docker run pcofilada/personal-website hugo version

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "Personal Website"
  env: "PersonalWebsite-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-737990757803"
  bucket_path: "Personal Website"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
